# Generated by Django 4.2.6 on 2023-10-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('diagnostics', models.TextField()),
                ('location', models.CharField(max_length=1000)),
                ('specialization', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('diagnostics', models.TextField()),
                ('observations', models.TextField()),
                ('treatment', models.TextField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
    ]
