# Generated by Django 4.2.6 on 2023-10-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_department_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='user',
            new_name='doctor_id',
        ),
    ]
