# Generated by Django 4.2.6 on 2023-10-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('D', 'doctor'), ('P', 'patient')], default='P', max_length=20),
        ),
    ]
